driver:
  name: docker
  use_sudo: false
  privileged: true
  forward:
    - 80

transport:
  name: sftp

provisioner:
  name: salt_solo
  salt_install: bootstrap
  is_file_root: true
  require_chef: false
  state_top:
    base:
      "*":
        - nginx.init
  pillars:
    top.sls:
      base:
        "*":
          - nginx
  pillars_from_files:
    nginx.sls: nginx-pillar.sls

platforms:
  - name: centos-7
    driver_config:
      run_command: /usr/lib/systemd/systemd

suites:
  - name: default

verifier:
  name: inspec
